language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    #- tools
    #- platform-tools

    # The BuildTools version used by your project
    - build-tools-25.0.0

    # The SDK version used to compile your project
    - android-25

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-22
    #- sys-img-armeabi-v7a-android-17

script:
- "./gradlew clean build assemble"


deploy:
  provider: releases
  api_key:
    secure: bS0MZdl1s2p70in1bgiuV9MofIJbkisRCWEPst5ZyKE+ngSlrGiPb15H6RRGx6+JdbcHhrOmxr7PVJ7LVs5/M/R5y4E1l81BqF4tVscRF/K/QJ6Lx6X1aytCd0l3H3OUD3prEk5JhL8Gc3ACRAmQEraCQQ6ua7F5AZo38LDXCDB3R4OD9TwiLqcSplSd73Tu/RhM3bs03FwrizbmbuZB7GURlsMfK4yNjCOUCQFXWOk63I2TzGfYZhVkzdbIi0AAzAqxYS9is+XXaHt0Twz2xAHklT7oiSK1pM9J7C5thqPwgbVuQQrMu+EqhtGooULVKZ3OXmVzbl8SAm9xPIzbNdwbZlHGFv+NQTtpeC1d+ma1HCxto8FtW6RgPTgmckWbOWoCv1bPDOr4UkiQlDzbigwyzBLpo5pSLUhSZgBV5txzljPKbGSaPmQfNFz81bCRu+qxUF150VBSJXbVkDT5i2EG3AcRBcIWuSlhl5qlJwu/UCRFcj7/41ksX8KCNRnoDOz1/HMpodhxOMGgR0jx2ufuw/GgfJL6LAqAtvUKpcKRh9lyvHMXlj0+4j7P6Rq9Gw1OFMu+eFFBjClz1UlfZUrf71dzlnhK90Jay/e7azp70WCI6nmMFi96N/qkmVPcpsZw7A3WpEHun3fsIamMvy8HLQcBZTzEx9szOJEqABM=
  # Which file(s) to upload
  file: app/build/outputs/apk/telephoto-1.5.11b-12-release-unsigned.apk
  skip_cleanup: true
  # only deploy if
  on:
    all_branches: true
    repo: Rai220/Telephoto
    tags: false

